# tap "homebrew/bundle"
# tap "homebrew/cask"
# tap "homebrew/cask-versions"
# tap "homebrew/core"
# brew "SwagGen"
# brew "autoconf"
# brew "automake"
# brew "bfg"
# brew "bluepill"
# brew "coreutils"
# brew "libksba"
# brew "libtool"
# brew "libyaml"
# brew "node"
# brew "openapi-generator"
# brew "openssl@1.1"
# brew "pkg-config"
# brew "readline"
# brew "shfmt"
# brew "swiftformat"
# brew "wget"
# brew "yarn"
# brew "zsh-autosuggestions"
# brew "zsh-syntax-highlighting"
# cask "android-platform-tools"
# cask "unetbootin"

brew "protobuf"
brew "swift-protobuf"