require 'open-uri'
require 'credentials_manager'
require 'dotenv/load'
require 'dotenv'
require 'json'
require 'uri'

default_platform(:ios)

def get_version_and_build   
  ENV['BUILD_NUMBER'] = sh("/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' '#{Dir.pwd}/../WavesWallet-iOS/Info.plist'").gsub!(/[^0-9A-Za-z]/, '')
  ENV['VERSION'] = get_version_number(xcodeproj: "#{ENV['ROOT_PROJECT']}/WavesWallet-iOS.xcodeproj")      
end

before_all do
  Dotenv.overload '.env'
  setup_circle_ci  

  ENV['CI_INIT']="true"

  sh("security find-identity -v -p codesigning fastlane_tmp_keychain")
  
  sh("security find-identity -v -p codesigning fastlane_tmp_keychain")  
  sh("ssh-keyscan -H bitbucket.org >> ~/.ssh/known_hosts")

  ENV['ROOT_PROJECT']= "#{Dir.pwd}/.."
  ENV['OUTPUT_PROJECT']= "#{Dir.pwd}/../Output"

  if Dir["#{ENV['OUTPUT_PROJECT']}"].empty? 
    sh("mkdir #{ENV['OUTPUT_PROJECT']}")  
  end
  
  get_version_and_build
    
  unless Helper.ci?
    sh("echo CI DONT USE")
    ENV['MATCH_KEYCHAIN_NAME']="login.keychain"
    ENV['CI_INIT']="false"
  end

end

platform :ios do

  lane :dev_enviroment do

    ENV['SCHEME_PROJECT'] ="WavesWallet-iOS-Dev"
    ENV['FASTLANE_APP_IDENTIFIER'] = "com.wavesplatform.waveswallet.dev"
    ENV['TESTFLIGHT_APP_IDENTITIFER'] = "com.wavesplatform.waveswallet.dev"
    ENV['MATCH_APP_IDENTIFIERS'] = "com.wavesplatform.waveswallet.dev"

    ENV['URL_FIREBASE'] = "#{ENV['URL_ROOT_CONFIG']}/GoogleService-Info-Dev.plist"
    ENV['URL_APPSFLYER'] = "#{ENV['URL_ROOT_CONFIG']}/Appsflyer-Info-Dev.plist"
    ENV['URL_AMPLITUDE'] = "#{ENV['URL_ROOT_CONFIG']}/Amplitude-Info-Prod.plist"
    ENV['URL_APPSPECTOR'] = "#{ENV['URL_ROOT_CONFIG']}/AppSpector-Info.plist"
    ENV['URL_SENTRY_IO'] = "#{ENV['URL_ROOT_CONFIG']}/Sentry-io-Info.plist"
    ENV['URL_FABRIC'] = "#{ENV['URL_ROOT_CONFIG']}/Fabric-Info.plist"
  
    ENV['EXPORT_OPTIONS'] = "#{Dir.pwd}/ExportOptions-AppStore.plist"

    ENV['MATCH_TYPE'] = "development"
    ENV['CHANGELOG_BETWEEN_BRANCH']="develop"
  end

  lane :prod_enviroment do

    ENV['SCHEME_PROJECT'] ="WavesWallet-iOS-Release"
    ENV['FASTLANE_APP_IDENTIFIER'] = "com.wavesplatform.WavesWallet"
    ENV['TESTFLIGHT_APP_IDENTITIFER'] = "com.wavesplatform.WavesWallet"
    ENV['MATCH_APP_IDENTIFIERS'] = "com.wavesplatform.waveswallet"

    ENV['URL_FIREBASE'] = "#{ENV['URL_ROOT_CONFIG']}/GoogleService-Info-Prod.plist"
    ENV['URL_APPSFLYER'] = "#{ENV['URL_ROOT_CONFIG']}/Appsflyer-Info-Prod.plist"
    ENV['URL_AMPLITUDE'] = "#{ENV['URL_ROOT_CONFIG']}/Amplitude-Info-Prod.plist"
    ENV['URL_APPSPECTOR'] = "#{ENV['URL_ROOT_CONFIG']}/AppSpector-Info.plist"
    ENV['URL_SENTRY_IO'] = "#{ENV['URL_ROOT_CONFIG']}/Sentry-io-Info.plist"
    ENV['URL_FABRIC'] = "#{ENV['URL_ROOT_CONFIG']}/Fabric-Info.plist"

    ENV['EXPORT_OPTIONS'] = "#{Dir.pwd}/ExportOptions-AppStore.plist"

    ENV['MATCH_TYPE'] = "appstore"
    ENV['CHANGELOG_BETWEEN_BRANCH']="master"
  end

  lane :test_enviroment do

    ENV['SCHEME_PROJECT'] ="WavesWallet-iOS-Test"
    ENV['FASTLANE_APP_IDENTIFIER'] = "com.wavesplatform.waveswallet.test"
    ENV['TESTFLIGHT_APP_IDENTITIFER'] = "com.wavesplatform.waveswallet.test"
    ENV['MATCH_APP_IDENTIFIERS'] = "com.wavesplatform.waveswallet.test"    

    ENV['URL_FIREBASE'] = "#{ENV['URL_ROOT_CONFIG']}/GoogleService-Info-Prod.plist"
    ENV['URL_APPSFLYER'] = "#{ENV['URL_ROOT_CONFIG']}/Appsflyer-Info-Prod.plist"
    ENV['URL_AMPLITUDE'] = "#{ENV['URL_ROOT_CONFIG']}/Amplitude-Info-Prod.plist"
    ENV['URL_APPSPECTOR'] = "#{ENV['URL_ROOT_CONFIG']}/AppSpector-Info.plist"
    ENV['URL_SENTRY_IO'] = "#{ENV['URL_ROOT_CONFIG']}/Sentry-io-Info.plist"
    ENV['URL_FABRIC'] = "#{ENV['URL_ROOT_CONFIG']}/Fabric-Info.plist"

    ENV['EXPORT_OPTIONS'] = "#{Dir.pwd}/ExportOptions-AdHoc.plist"

    ENV['MATCH_TYPE'] = "adhoc"
    ENV['CHANGELOG_BETWEEN_BRANCH']="master"    
  end

  lane :test_build_projet do
    test_enviroment
    increment_build_number_and_commit_push
    build_projet    
  end

  lane :test_upload_testflight do
    test_enviroment
    upload_testflight
  end

  lane :prod_build_projet do
    prod_enviroment
    increment_build_number_and_commit_push
    build_projet    
  end

  lane :prod_upload_testflight do
    prod_enviroment
    upload_testflight 
  end

  lane :dev_build_projet do
    dev_enviroment
    increment_build_number_and_commit_push
    build_projet
  end

  lane :dev_add_new_devices do
    dev_enviroment
    add_new_devices
  end

  lane :dev_install do
    dev_enviroment
    download_certificates
    download_resources
  end

  lane :dev_download_resources do
    dev_enviroment    
    download_resources
  end

  lane :build_projet do

    download_certificates
    download_resources

    name = "#{ENV['SCHEME_PROJECT']}-v#{ENV['VERSION']}-#{ENV['BUILD_NUMBER']}"
		gym(scheme: "#{ENV['SCHEME_PROJECT']}",
        workspace: "WavesWallet-iOS.xcworkspace",
        include_bitcode: true,
        include_symbols: true,
        export_options: "#{ENV['EXPORT_OPTIONS']}",
        output_directory: "#{ENV['OUTPUT_PROJECT']}",
        output_name: name
    )
  end

  lane :create_changelog do    
    puts "create_changelog"
    
    ENV['FL_BUILD_NUMBER_PROJECT'] = "#{ENV['ROOT_PROJECT']}/WavesWallet-iOS.xcodeproj"
    build_number = sh("/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' '#{Dir.pwd}/../WavesWallet-iOS/Info.plist'")
    version = get_version_number(xcodeproj: "#{ENV['ROOT_PROJECT']}/WavesWallet-iOS.xcodeproj")
    commit = last_git_commit
    author = commit[:author] # author of the commit
    author_email = commit[:author_email] # email of the author of the commit
    hash = commit[:commit_hash] # long sha of commit
    short_hash = commit[:abbreviated_commit_hash] # short sha of commit

    changelog = changelog_from_git_commits(
      between: [ENV['CHANGELOG_BETWEEN_BRANCH'], hash],  # Optional, lets you specify a revision/tag range between which to collect commit info
      pretty: "- %ad %s \n",# Optional, lets you provide a custom format to apply to each commit when generating the changelog text
      date_format: "short",# Optional, lets you provide an additional date format to dates within the pretty-formatted string
      match_lightweight_tag: false,  # Optional, lets you ignore lightweight (non-annotated) tags when searching for the last tag
      merge_commit_filtering: "exclude_merges" # Optional, lets you filter out merge commits
    )

    ENV['CHANGELOG']="Version: #{version} #{build_number}\n#{changelog}"
  end

  lane :upload_crashlytics do

    create_changelog

    ENV['CRASHLYTICS_API_TOKEN']=sh("/usr/libexec/PlistBuddy -c 'Print :Fabric:APIKey' '#{Dir.pwd}/../WavesWallet-iOS/Resources/Fabric-Info.plist'")
    ENV['CRASHLYTICS_API_TOKEN']="#{ENV['CRASHLYTICS_API_TOKEN']}"
    ENV['CRASHLYTICS_BUILD_SECRET']=sh("/usr/libexec/PlistBuddy -c 'Print :Fabric:BuildSecret' '#{Dir.pwd}/../WavesWallet-iOS/Resources/Fabric-Info.plist'")
    ENV['CRASHLYTICS_BUILD_SECRET']="#{ENV['CRASHLYTICS_BUILD_SECRET']}"
    ROOT=File.expand_path("..", Dir.pwd)
    ENV['SUMBIT_PAPTH']="#{ROOT}/Pods/Crashlytics/submit"
    ENV['IPA_PATH']="#{GYM_OUTPUT_DIRECTORY}/#{GYM_OUTPUT_NAME}"
    
    puts "upload_crashlytics"
    sh("bash #{Dir.pwd}/run_fabric.sh")

    upload_symbols_to_crashlytics(gsp_path: "#{Dir.pwd}/../WavesWallet-iOS/Resources/GoogleService-Info.plist")

  end

  lane :download_certificates do
    
    match(app_identifier: ENV['MATCH_APP_IDENTIFIERS'].split(","),
      git_url: "#{ENV['URL_CERTIFICATES_GIT']}",
      username: "#{ENV['APPLE_DEV_PORTAL_ID']}",
      type: "#{ENV['MATCH_TYPE']}",
      readonly: true,
      keychain_name: "#{ENV['MATCH_KEYCHAIN_NAME']}"
    )
  end

  lane :download_resources do
    sh("rm -rf #{Dir.pwd}/../WavesWallet-iOS/Resources/Fabric-Info.plist")
    sh("curl -X GET -H 'Authorization: Basic #{ENV['AUTH_KEY_OPTIONS']}' #{ENV['URL_FABRIC']} >> #{Dir.pwd}/../WavesWallet-iOS/Resources/Fabric-Info.plist")

    sh("rm -rf #{Dir.pwd}/../WavesWallet-iOS/Resources/GoogleService-Info.plist")
    sh("curl -X GET -H 'Authorization: Basic #{ENV['AUTH_KEY_OPTIONS']}' #{ENV['URL_FIREBASE']} >> #{Dir.pwd}/../WavesWallet-iOS/Resources/GoogleService-Info.plist")

    sh("rm -rf #{Dir.pwd}/../WavesWallet-iOS/Resources/Appsflyer-Info.plist")
    sh("curl -X GET -H 'Authorization: Basic #{ENV['AUTH_KEY_OPTIONS']}' #{ENV['URL_APPSFLYER']} >> #{Dir.pwd}/../WavesWallet-iOS/Resources/Appsflyer-Info.plist")

    sh("rm -rf #{Dir.pwd}/../WavesWallet-iOS/Resources/AppSpector-Info.plist")
    sh("curl -X GET -H 'Authorization: Basic #{ENV['AUTH_KEY_OPTIONS']}' #{ENV['URL_APPSPECTOR']} >> #{Dir.pwd}/../WavesWallet-iOS/Resources/AppSpector-Info.plist")

    sh("rm -rf #{Dir.pwd}/../WavesWallet-iOS/Resources/Sentry-io-Info.plist")
    sh("curl -X GET -H 'Authorization: Basic #{ENV['AUTH_KEY_OPTIONS']}' #{ENV['URL_SENTRY_IO']} >> #{Dir.pwd}/../WavesWallet-iOS/Resources/Sentry-io-Info.plist")

    sh("rm -rf #{Dir.pwd}/../WavesWallet-iOS/Resources/Amplitude-Info.plist")
    sh("curl -X GET -H 'Authorization: Basic #{ENV['AUTH_KEY_OPTIONS']}' #{ENV['URL_SENTRY_IO']} >> #{Dir.pwd}/../WavesWallet-iOS/Resources/Amplitude-Info.plist")
  end

  lane :download_bundle_enviroments do
    sh("rm -rf #{Dir.pwd}/../.env")
    sh("curl -X GET -H 'Authorization: Basic #{ENV['AUTH_KEY_OPTIONS']}' #{ENV['URL_BUNDLE_ENV']} >> #{Dir.pwd}/../.env")
  end

  lane :add_new_devices do
    
    match(app_identifier: ENV['MATCH_APP_IDENTIFIERS'].split(","),
          git_url: "#{ENV['URL_CERTIFICATES_GIT']}",
          username: "#{ENV['APPLE_DEV_PORTAL_ID']}",
          type: "#{ENV['MATCH_TYPE']}",
          force_for_new_devices: true,
          keychain_name: "#{ENV['MATCH_KEYCHAIN_NAME']}")
  end

  lane :upload_testflight do

    create_changelog

    if ENV['CHANGELOG'].to_s.empty?
      ENV['CHANGELOG'] = "Not Found"
    end

    PROJECT_IPA = "#{ENV['SCHEME_PROJECT']}-v#{ENV['VERSION']}-#{ENV['BUILD_NUMBER']}"
    PROJECT_IPA = "#{ENV['OUTPUT_PROJECT']}/#{PROJECT_IPA}.ipa"
    
    testflight(username: "#{ENV['APPLE_DEV_PORTAL_ID']}",
               itc_provider: "#{ENV['FASTLANE_ITC_TEAM_ID']}",
               wait_for_uploaded_build: "false",
               changelog: "#{ENV['CHANGELOG']}",
               ipa: PROJECT_IPA)
        
    upload_symbols_to_crashlytics(gsp_path: "#{Dir.pwd}/../WavesWallet-iOS/Resources/GoogleService-Info.plist")              
  end

  lane :send_to_slack_artifacts  do
      
    URL_ARTIFACTS = "https://circleci.com/api/v1.1/project/github/wavesplatform/WavesWallet-iOS/#{ENV['CIRCLE_BUILD_NUM']}/artifacts?circle-token=#{ENV['CIRCLE_CI_TOKEN']}"

    JSON_ARTIFACTS = "#{ENV['OUTPUT_PROJECT']}/artifacts.json"

    sh("rm -rf #{JSON_ARTIFACTS}")    
    sh('curl -X GET "' + URL_ARTIFACTS + '" >> "' + JSON_ARTIFACTS + '"')

    file = File.read("#{JSON_ARTIFACTS}")
    artifacts = JSON.parse(file)

    if artifacts.count > 0
      fields = []

      artifacts.each { |artifact|
        
        name = URI(artifact["path"]).path.split('/').last
        url = artifact["url"]
  
        field_artifact = []
  
        fields.push({
          "title": name,
          "value": url          
        })      
      }
    
      slack(message: "🤖 CI Build #{ENV['CIRCLE_BUILD_NUM']}",
            pretext: "Artifacts Version iOS #{ENV['VERSION']}-#{ENV['BUILD_NUMBER']}",
            username: "BurningMan",
            icon_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2IOUZkkfdAaYMVpGkzNZr-cEv855jpVuI79UaHE2dE8SLACJW",          
            default_payloads: [],
            attachment_properties: {
              fields: fields
            } 
         )
    else
      slack(message: "🤖 CI Build #{ENV['CIRCLE_BUILD_NUM']}",
        pretext: "Artifacts not founds Version iOS #{ENV['VERSION']}-#{ENV['BUILD_NUMBER']}",
        username: "BurningMan",
        icon_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2IOUZkkfdAaYMVpGkzNZr-cEv855jpVuI79UaHE2dE8SLACJW",          
        default_payloads: [],
        success: false
     )
    end
  end

  lane :increment_build_number_and_commit_push do      
      increment_build_number

      git_commit(path: "#{ENV['ROOT_PROJECT']}/WavesWallet-iOS/Info.plist", message: "Increment build number")
      push_to_git_remote
  end

  # lane :init_project do 
  
	# 	cocoapods(
	# 		verbose: true,
	# 		clean: true,
	# 		use_bundle_exec: false
  #   )
    
  # end
end
