//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: adcash_deposits.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate Acash_ACashDepositsClient, then call methods of this protocol to make API calls.
public protocol Acash_ACashDepositsClientProtocol {
  func registerOrder(_ request: Acash_RegisterOrderRequest, callOptions: CallOptions?) -> UnaryCall<Acash_RegisterOrderRequest, Acash_RegisterOrderResponse>
  func getACashAssets(_ request: Acash_GetACashAssetsRequest, callOptions: CallOptions?) -> UnaryCall<Acash_GetACashAssetsRequest, Acash_GetACashAssetsResponse>
  func getACashAssetsExchangeRate(_ request: Acash_GetACashAssetsExchangeRateRequest, callOptions: CallOptions?) -> UnaryCall<Acash_GetACashAssetsExchangeRateRequest, Acash_GetACashAssetsExchangeRateResponse>
}

public final class Acash_ACashDepositsClient: GRPCClient, Acash_ACashDepositsClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the acash.ACashDeposits service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// Unary call to RegisterOrder
  ///
  /// - Parameters:
  ///   - request: Request to send to RegisterOrder.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func registerOrder(_ request: Acash_RegisterOrderRequest, callOptions: CallOptions? = nil) -> UnaryCall<Acash_RegisterOrderRequest, Acash_RegisterOrderResponse> {
    return self.makeUnaryCall(path: "/acash.ACashDeposits/RegisterOrder",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

  /// Unary call to GetACashAssets
  ///
  /// - Parameters:
  ///   - request: Request to send to GetACashAssets.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getACashAssets(_ request: Acash_GetACashAssetsRequest, callOptions: CallOptions? = nil) -> UnaryCall<Acash_GetACashAssetsRequest, Acash_GetACashAssetsResponse> {
    return self.makeUnaryCall(path: "/acash.ACashDeposits/GetACashAssets",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

  /// Unary call to GetACashAssetsExchangeRate
  ///
  /// - Parameters:
  ///   - request: Request to send to GetACashAssetsExchangeRate.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getACashAssetsExchangeRate(_ request: Acash_GetACashAssetsExchangeRateRequest, callOptions: CallOptions? = nil) -> UnaryCall<Acash_GetACashAssetsExchangeRateRequest, Acash_GetACashAssetsExchangeRateResponse> {
    return self.makeUnaryCall(path: "/acash.ACashDeposits/GetACashAssetsExchangeRate",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

}


// Provides conformance to `GRPCPayload` for request and response messages
extension Acash_RegisterOrderRequest: GRPCProtobufPayload {}
extension Acash_RegisterOrderResponse: GRPCProtobufPayload {}
extension Acash_GetACashAssetsRequest: GRPCProtobufPayload {}
extension Acash_GetACashAssetsResponse: GRPCProtobufPayload {}
extension Acash_GetACashAssetsExchangeRateRequest: GRPCProtobufPayload {}
extension Acash_GetACashAssetsExchangeRateResponse: GRPCProtobufPayload {}

