platform :ios, '11.0'

# Ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!(true)

# Pods for WavesWallet-iOS
target 'KeeperExample' do    
    project 'KeeperExample.xcodeproj'    
    
    pod "WavesSDK", :git => "git@github.com:wavesplatform/WavesSDK-iOS.git", :branch => "develop" 
    pod 'CryptoSwift'
    pod 'TextFieldEffects'

end
